[0m16:55:48.758519 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002209773AF90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022098AC9210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022098587ED0>]}


============================== 16:55:48.764502 | 2d614893-9fce-402a-8756-406bf5eecf5a ==============================
[0m16:55:48.764502 [info ] [MainThread]: Running with dbt=1.6.17
[0m16:55:48.766497 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:55:48.768492 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\fajlh\OneDrive\Documents\DBT_demo\DBT_demo\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:55:48.771485 [debug] [MainThread]: Command `dbt deps` failed at 16:55:48.771485 after 0.06 seconds
[0m16:55:48.773479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022098A3FDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022092A14A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022099319A10>]}
[0m16:55:48.774477 [debug] [MainThread]: Flushing usage events
[0m19:07:11.455894 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000201BB6BDE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000201BB9D2A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000201BB6A9090>]}


============================== 19:07:11.467500 | aa68aeb1-3b98-4b79-b536-39e81090133c ==============================
[0m19:07:11.467500 [info ] [MainThread]: Running with dbt=1.6.17
[0m19:07:11.471801 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run -s companies_transaction_products-', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:07:11.473795 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\fajlh\OneDrive\Documents\DBT_demo\DBT_demo\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:07:11.485681 [debug] [MainThread]: Command `dbt run` failed at 19:07:11.485681 after 0.14 seconds
[0m19:07:11.487742 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000201BB6AA950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000201B5914B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000201BC206C50>]}
[0m19:07:11.489052 [debug] [MainThread]: Flushing usage events
[0m19:07:31.522695 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE84B8D0D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE8564C0D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE856C8C90>]}


============================== 19:07:31.533042 | 68eaf6a8-aefa-4eac-839f-91eb11037e1d ==============================
[0m19:07:31.533042 [info ] [MainThread]: Running with dbt=1.6.17
[0m19:07:31.535851 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run -s companies_transaction_products', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:07:31.537892 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\fajlh\OneDrive\Documents\DBT_demo\DBT_demo\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:07:31.542366 [debug] [MainThread]: Command `dbt run` failed at 19:07:31.541842 after 0.08 seconds
[0m19:07:31.543704 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AEFF614B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE8564D150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AEFFA99DD0>]}
[0m19:07:31.545363 [debug] [MainThread]: Flushing usage events
[0m20:28:58.656153 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A174CC0F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A174CAB810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A174F45550>]}


============================== 20:28:58.664132 | 6f8d8352-64be-46b9-af9f-839e6894c218 ==============================
[0m20:28:58.664132 [info ] [MainThread]: Running with dbt=1.6.17
[0m20:28:58.666127 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run -s tag:base_table', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m20:28:58.669120 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\fajlh\OneDrive\Documents\DBT_demo\DBT_demo\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:28:58.673111 [debug] [MainThread]: Command `dbt run` failed at 20:28:58.672112 after 0.08 seconds
[0m20:28:58.674110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A16EF14AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A174F28950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A16F052A10>]}
[0m20:28:58.676102 [debug] [MainThread]: Flushing usage events
